============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-5.4.2, py-1.5.2, pluggy-0.13.1
benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/ptisnovs/src/python/testing-in-python/pytest/average3
plugins: voluptuous-1.0.2, benchmark-3.2.3, cov-2.5.1
collected 1 item

test_average.py F                                                        [100%]

=================================== FAILURES ===================================
______________________________ test_average_basic ______________________________

    def test_average_basic():
        """Otestování výpočtu průměru."""
        result = average([1,2])
        expected = 1.5
>       assert result == expected, "Očekávaná hodnota {}, vráceno {}".format(expected, result)
E       AssertionError: Očekávaná hodnota 1.5, vráceno 1.0
E       assert 1.0 == 1.5

test_average.py:10: AssertionError

----------- coverage: platform linux, python 3.6.6-final-0 -----------
Name         Stmts   Miss  Cover   Missing
------------------------------------------
average.py       2      0   100%

=========================== short test summary info ============================
FAILED test_average.py::test_average_basic - AssertionError: Očekávaná hodnot...
============================== 1 failed in 0.04s ===============================
